In [1]:
import pandas as pd
import numpy as np

In [2]:
a=np.random.randint(20,60,15)

In [3]:
a

array([56, 31, 47, 58, 59, 29, 37, 20, 45, 27, 37, 33, 30, 52, 57])

In [4]:
a[0]


56

In [5]:
a[7]

20

In [6]:
a[-4]

33

In [ ]:
#seed function makes sure that the date is not changing

In [15]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[76, 55, 71, 70, 67, 70, 54, 54],
       [68, 76, 71, 73, 60, 60, 74, 58],
       [57, 73, 76, 59, 73, 49, 61, 70],
       [75, 65, 75, 64, 56, 57, 53, 58],
       [76, 73, 63, 50, 65, 52, 48, 51],
       [77, 46, 47, 63, 69, 60, 74, 57],
       [76, 56, 77, 72, 48, 58, 66, 68]])

In [16]:
b.ndim

2

In [17]:
b[-1] # last row

array([76, 56, 77, 72, 48, 58, 66, 68])

In [18]:
b[3] # 3rd row

array([75, 65, 75, 64, 56, 57, 53, 58])

In [ ]:
# to access a column we need to add " :, "

In [19]:
b[:,7] # 7th column

array([54, 58, 70, 58, 51, 57, 68])

In [20]:
b[:,4] # 4th column

array([67, 60, 73, 56, 65, 69, 48])

In [22]:
b[1,3] # 1st row and 3rd column position

73

In [23]:
b[5,6] # 5th row and 6th column position

74

In [24]:
b

array([[76, 55, 71, 70, 67, 70, 54, 54],
       [68, 76, 71, 73, 60, 60, 74, 58],
       [57, 73, 76, 59, 73, 49, 61, 70],
       [75, 65, 75, 64, 56, 57, 53, 58],
       [76, 73, 63, 50, 65, 52, 48, 51],
       [77, 46, 47, 63, 69, 60, 74, 57],
       [76, 56, 77, 72, 48, 58, 66, 68]])

In [ ]:
# left part of (,) reseverd for rows and right part of( ,) is reserved for the columns

In [27]:
b[2,1:6]

array([73, 76, 59, 73, 49])

In [ ]:
array[row_start:row_end:row_stop, col_start:col_end:col_step]

In [31]:
b

array([[76, 55, 71, 70, 67, 70, 54, 54],
       [68, 76, 71, 73, 60, 60, 74, 58],
       [57, 73, 76, 59, 73, 49, 61, 70],
       [75, 65, 75, 64, 56, 57, 53, 58],
       [76, 73, 63, 50, 65, 52, 48, 51],
       [77, 46, 47, 63, 69, 60, 74, 57],
       [76, 56, 77, 72, 48, 58, 66, 68]])

In [32]:
b[1:6]

array([[68, 76, 71, 73, 60, 60, 74, 58],
       [57, 73, 76, 59, 73, 49, 61, 70],
       [75, 65, 75, 64, 56, 57, 53, 58],
       [76, 73, 63, 50, 65, 52, 48, 51],
       [77, 46, 47, 63, 69, 60, 74, 57]])

In [34]:
b[1:6:2] #row indexing and row slicing

array([[68, 76, 71, 73, 60, 60, 74, 58],
       [75, 65, 75, 64, 56, 57, 53, 58],
       [77, 46, 47, 63, 69, 60, 74, 57]])

In [35]:
b[1:6:2,1:6] # row indexing,row slicing and column indexing,column slicing

array([[76, 71, 73, 60, 60],
       [65, 75, 64, 56, 57],
       [46, 47, 63, 69, 60]])

In [38]:
b[3:6,2:6]

array([[75, 64, 56, 57],
       [63, 50, 65, 52],
       [47, 63, 69, 60]])

In [39]:
b

array([[76, 55, 71, 70, 67, 70, 54, 54],
       [68, 76, 71, 73, 60, 60, 74, 58],
       [57, 73, 76, 59, 73, 49, 61, 70],
       [75, 65, 75, 64, 56, 57, 53, 58],
       [76, 73, 63, 50, 65, 52, 48, 51],
       [77, 46, 47, 63, 69, 60, 74, 57],
       [76, 56, 77, 72, 48, 58, 66, 68]])

In [42]:
b[1:6:2]

array([[68, 76, 71, 73, 60, 60, 74, 58],
       [75, 65, 75, 64, 56, 57, 53, 58],
       [77, 46, 47, 63, 69, 60, 74, 57]])

In [43]:
b[1:6:2,1:8:3]

array([[76, 60, 58],
       [65, 56, 58],
       [46, 69, 57]])